name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        uses: borales/actions-yarn@v4
        with: 
          cmd: install
          dir: './packages/realtoken-commons'
      - name: Build
        uses: borales/actions-yarn@v4
        with: 
          cmd: build
          dir: './packages/realtoken-commons'
      - name: Publish
        uses: borales/actions-yarn@v4
        with: 
          cmd: publish --access public
          dir: './packages/realtoken-commons'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}